name: OptEco
version: 1.5.1b
api-version: 1.13
main: me.playernguyen.opteco.OptEco
author: Player_Nguyen
softdepend:
  - PlaceholderAPI
  - ProtocolLib

commands:
  opteco:
    usage: /opteco help
  points:
    usage: /opteco help