name: OptEco
version: 1.4.7b
api-version: 1.13
main: me.playernguyen.OptEco
author: Player_Nguyen
softdepend:
  - PlaceholderAPI

commands:
  opteco:
    usage: /opteco help
  points:
    usage: /opteco help