name: OptEco
version: 1.6b
api-version: 1.13
description: "The points system plugin"
main: me.playernguyen.opteco.OptEco
author: Player_Nguyen
softdepend:
  - PlaceholderAPI
  - ProtocolLib
commands:
  opteco:
    usage: /opteco help
    description: The OptEco main command
    aliases: [points, pts, p]